# Generated by Django 4.2.4 on 2023-08-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='forget_user',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
